dist: focal
language: python
os: linux

install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports > /dev/null
  - sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc' > /dev/null
  - sudo add-apt-repository -y 'deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal main' > /dev/null
  - sudo apt-get install -y golang-go python3-mysqldb wget rsync minify npm > /dev/null
  - export GOPATH=/tmp/go && go get github.com/Clever/csvlint/cmd/csvlint > /dev/null
  - pip install -r .exporter/requirements.txt > /dev/null
  - npm install --global uglify-js uglifycss > /dev/null

before_script:
  - ./.exporter/import_check.sh
  - ./.exporter/check_plz_against_database.py
  - ./.download/prepare.sh # This needs to be done before the exporters run

script:
  - ./.exporter/exporter.sh
  - ./.exporter/export_check.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - echo "auskunftsbegehren-adressen.cyber-perikarp.eu" > upload/CNAME
  - ./.download/minify.sh # Minify html, css and js

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: upload
  strategy: git
  edge: true
  skip_cleanup: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: master
