dist: focal
language: python
os: linux

install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports
  - sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
  - sudo add-apt-repository -y 'deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal main'
  - sudo apt-get update
  - sudo apt-get install -y golang-go python3-mysqldb figlet wget rsync nodejs npm
  - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb || true
  - sudo apt-get -f -y install
  - rm wkhtmltox_0.12.6-1.focal_amd64.deb
  - export GOPATH=/tmp/go && go get github.com/Clever/csvlint/cmd/csvlint
  - pip install -r .exporter/requirements.txt
  - npm install --global uglify-js uglifycss

before_script:
  - figlet "IMPORT CHECK"; ./.exporter/import_check.sh
  - figlet "PLZ CHECK"; ./.exporter/check_plz_against_database.py
  - figlet "DOWNLOAD PAGE"; ./.download/prepare.sh # This needs to be done before the exporters run

script:
  - figlet "EXPORT"; ./.exporter/exporter.sh
  - figlet "EXPORT CHECK"; ./.exporter/export_check.sh

before_deploy:
  - figlet "DEPLOY"
  - cd $TRAVIS_BUILD_DIR
  - echo "auskunftsbegehren-adressen.cyber-perikarp.eu" > upload/CNAME

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: upload
  strategy: git
  edge: true
  skip_cleanup: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: master
